//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class HDGiaoHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDGiaoHang()
        {
            this.CTHDGiaoHangs = new HashSet<CTHDGiaoHang>();
        }

        public int Ma { get; set; }
        public string GiamGia { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> ThoiGianNhan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDGiaoHang> CTHDGiaoHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
