//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DoanhThu
    {
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string LoaiHD { get; set; }
        public Nullable<int> TongTien { get; set; }
    }
}
